accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as authViews

app_name= "accounts"
urlpatterns = [
   
    path('register/', views.register,name="register"),
    path('login/', views.userLogin,name="login"),
    path('logout/', views.userLogout,name="logout"),
    path('password/', views.password_change, name='password_change'),
    path('profile/', views.profile, name='profile'),
    path('update/', views.user_update, name='user_update'),
    path('user_order/', views.user_order, name='user_order'),
    path('user_comment/', views.user_comment, name='user_comment'),
    path('deletecomment/<int:id>', views.user_deletecomment, name='user_deletecomment'),
    path('user_order_detail/<int:id>', views.user_orderdetail, name='user_order_detail'),
    path('orders_product/', views.user_order_product, name='user_order_product'),
    path('order_product_detail/<int:id>/<int:oid>', views.user_order_product_detail, name='user_order_product_detail'),
    #************Forgot password***************************
    path('reset_password/', authViews.PasswordResetView.as_view(
        template_name="auth/password_reset.html"), name="reset_password"),
     path('reset_password_sent/', authViews.PasswordResetDoneView.as_view(
         template_name="auth/password_reset_done.html"), name="password_reset_done"),
    path('reset/<uidb64>/<token>/', authViews.PasswordResetConfirmView.as_view(
        template_name="auth/password_reset_confirm.html"), name="password_reset_confirm"),
    path('reset_password_complete/', authViews.PasswordResetCompleteView.as_view(
        template_name="auth/password_reset_done.html"), name="password_reset_complete"),
        #************************************************************#
    
   
    
]

cart/urls.py
from django.urls import path
from . import views
app_name= "cart"
urlpatterns = [
   
    path('checkout/', views.checkout,name="checkout"),
    path('addtoshopcart/<int:id>', views.addtoshopcart, name='addtoshopcart'),
    path('deletefromcart/<int:id>', views.deletefromcart, name='deletefromcart'),
    path('shopcart/', views.shopcart, name='shopcart'),
    path('orderproduct/', views.orderproduct, name='orderproduct'),
    
]

ecommerce_project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf  import settings
from home import views


urlpatterns = [
    path('admin/', admin.site.urls),
   
   #path('', views.index, name='home'),
    path('', include('home.urls',namespace='home')),
    path('cart/', include('cart.urls',namespace='cart')),
    path('product/', include('product.urls',namespace='product')),
    path('account/', include('accounts.urls',namespace='accounts')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views

app_name= "home"
urlpatterns = [
   
    path('', views.index,name="home"),
    path('category/<int:id>/<slug:slug>', views.category_products, name='category_products'),
    path('product_deatil/<int:id>/<slug:slug>', views.product_detail, name='product_detail'),
    path('search/', views.search, name='search'),
    path('search_auto/', views.search_auto, name='search_auto'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    
]

product/urls.py
from django.urls import path
from . import views
app_name= "product"
urlpatterns = [
   
    path('product_detail/', views.detail,name="product_detail"),
    path('product_list/', views.product,name="product_list"),
    path('addcomment/<int:id>', views.addcomment,name="addcomment"),
   
    
]

home/models.py
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField
# Create your models here.
class Setting(models.Model):
    STATUS = (
        ('True', 'True'),
        ('False', 'False'),
    )
    title = models.CharField(max_length=150)
    keywords = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    company = models.CharField(max_length=50)
    address = models.CharField(blank=True,max_length=100)
    phone = models.CharField(blank=True,max_length=15)
    fax = models.CharField(blank=True,max_length=15)
    email = models.CharField(blank=True,max_length=50)
    smtpserver = models.CharField(blank=True,max_length=50)
    smtpemail = models.CharField(blank=True,max_length=50)
    smtppassword = models.CharField(blank=True,max_length=10)
    smtpport = models.CharField(blank=True,max_length=5)
    icon = models.ImageField(blank=True,upload_to='images/')
    facebook = models.CharField(blank=True,max_length=50)
    instagram = models.CharField(blank=True,max_length=50)
    twitter = models.CharField(blank=True,max_length=50)
    youtube = models.CharField(blank=True, max_length=50)
    aboutus = RichTextUploadingField(blank=True)
    contact = RichTextUploadingField(blank=True)
    references = RichTextUploadingField(blank=True)
    status=models.CharField(max_length=10,choices=STATUS)
    create_at=models.DateTimeField(auto_now_add=True)
    update_at=models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

class Contact(models.Model):
    STATUS = (
        ('New', 'New'),
        ('Read', 'Read'),
        ('Closed', 'Closed'),
    )
    name= models.CharField(blank=True,max_length=20)
    email= models.CharField(blank=True,max_length=50)
    subject= models.CharField(blank=True,max_length=50)
    message= models.TextField(blank=True,max_length=255)
    status=models.CharField(max_length=10,choices=STATUS,default='New')
    ip = models.CharField(blank=True, max_length=20)
    note = models.CharField(blank=True, max_length=100)
    create_at=models.DateTimeField(auto_now_add=True)
    update_at=models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

class FAQ(models.Model):
    STATUS = (
        ('True', 'True'),
        ('False', 'False'),
    )
   #lang =  models.CharField(max_length=6, choices=langlist, blank=True, null=True)
    ordernumber = models.IntegerField()
    question = models.CharField(max_length=200)
    answer = RichTextUploadingField()
    status=models.CharField(max_length=10, choices=STATUS)
    create_at=models.DateTimeField(auto_now_add=True)
    update_at=models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.question

home/forms.py
from django import forms 
from django.forms import ModelForm
from .models import *
class searchForm(forms.Form):
    query=forms.CharField(max_length=100)
    catid=forms.IntegerField()

class contactMessage(ModelForm):
    class Meta:
        model=Contact
        fields=['name','email','subject','message'] 

home/views.py
import json
from django.shortcuts import render
from product.models import *
from django.http import HttpResponse,HttpResponseRedirect
import datetime
from .forms import *
from .models import *
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from cart.models import ShopCart


# Create your views here.
@login_required(login_url='accounts:login')
def index(request):
    product_slider=Product.objects.order_by('?')[:4]
    latest_product=Product.objects.order_by('-id')[:4]
    picked_product=Product.objects.order_by('?')[:4]
    current_user=request.user
    shopcart=ShopCart.objects.filter(user_id=current_user.id)
    cartpro=shopcart.count()
    #page="home"
    context={
        #"page":page,
        "product_slider": product_slider,
        "latest_product":latest_product,
        "picked_product":picked_product,
        'cartpro':cartpro
        
    }
    return render(request,'home/index.html',context)

@login_required(login_url='accounts:login')
def category_products(request,id,slug):
   category = Category.objects.get(pk=id)
   products = Product.objects.filter(category_id=id)
   context={"products":products
                }
   return render(request,'home/category_products.html',context)

@login_required(login_url='accounts:login')
def product_detail(request,id,slug):
    product=Product.objects.get(pk=id)
    image=Images.objects.filter(product_id=id)
    comment =Comment.objects.filter(product_id=id,status=True)
    related_product=Product.objects.filter(category_id=product.category_id).exclude(pk=product.id).order_by('?')[:4]
    context={"product":product,
             "image":image ,
             "comment":comment,
             "related_product":related_product
            }
    return render(request,'home/product_detail.html',context)

def search(request):
    if request.method == 'GET': # check post
        form = searchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query'] # get form input data
            catid = form.cleaned_data['catid']
            if catid==0:
                products=Product.objects.filter(title__icontains=query)  #SELECT * FROM product WHERE title LIKE '%query%'
            else:
                products = Product.objects.filter(title__icontains=query,category_id=catid)

            category = Category.objects.all()
            context = {'product': products, 'query':query,
                       'category': category }
            return render(request, 'home/search_product.html', context)

    return HttpResponseRedirect('/')

def search_auto(request):
    if request.is_ajax():
        q = request.GET.get('term', '')
        products = Product.objects.filter(title__icontains=q)

        results = []
        for item in products:
            product_json = {}
            product_json = item.title
            results.append(product_json)
        data = json.dumps(results)
    else:
        data = 'fail'
    mimetype = 'application/json'
    return HttpResponse(data, mimetype)    

def about(request):
    setting=Setting.objects.get(pk=1)
    context={"setting":setting}
    return render(request,'home/about.html',context)

def contact(request):
    setting=Setting.objects.get(pk=1)
    url=request.META.get('HTTP_REFERER')
    if request.method=='POST':
      form=contactMessage(request.POST)
      if form.is_valid():
          data=Contact()
          data.name=form.cleaned_data.get('name')
          data.email=form.cleaned_data.get('email')
          data.subject=form.cleaned_data.get('subject')
          data.message=form.cleaned_data.get('message')
          data.ip=request.META.get('REMOTE_ADDR')
          data.save()
          messages.success(request,'your message added successfully')
          return HttpResponseRedirect(url)

    
    context={"setting":setting}
    return render(request,'home/contact.html',context)

home/templates/home/about.html
{% extends 'home/base.html' %}

{% block navbar %} {% include 'home/navbar.html' %} {% endblock %}


{% load static %}
{% block content %}

	<!-- section -->
	<div class="section">
		<!-- container -->
		<div class="container">
			<!-- row -->
			<div class="row">

         {{setting.aboutus|safe}}

			</div>
			<!-- /row -->
		</div>
		<!-- /container -->
	</div>
	<!-- /section -->

	{% endblock %}

home/templates/home/base.html
 {% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

	<title> My Home Page </title>
    
	<!-- Google font -->
	<link href="https://fonts.googleapis.com/css?family=Hind:400,700" rel="stylesheet">
	<!-- CSS only -->

   
	<!-- Bootstrap -->
	<link type="text/css" rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />

	<!-- Slick -->
	<link type="text/css" rel="stylesheet" href="{% static 'css/slick.css' %}" />
	<link type="text/css" rel="stylesheet" href="{% static 'css/slick-theme.css' %}" />

	<!-- nouislider -->
	<link type="text/css" rel="stylesheet" href="{% static 'css/nouislider.min.css' %}" />

	<!-- Font Awesome Icon -->
	<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">

	<!-- Custom stlylesheet -->
	<link type="text/css" rel="stylesheet" href="{% static 'css/style.css' %}" />

	<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
		  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
		  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		<![endif]-->
<!-- jQuery !-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"> </script>
	<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>
    <!-- jQuery UI !-->
   <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/themes/smoothness/jquery-ui.css">


</head>

<body>
	{% include 'home/header.html' %}
	{% block navbar %}{% endblock %}
    {% block slider %}{% endblock %}
    {% block content %}{% endblock %}
    {% include 'home/footer.html' %}

	<!-- jQuery Plugins -->
	
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	<script src="{% static 'js/slick.min.js' %}"></script>
	<script src="{% static 'js/nouislider.min.js' %}"></script>
	<script src="{% static 'js/jquery.zoom.min.js' %}"></script>
	<script src="{% static 'js/main.js' %}"></script>

</body>

</html>

home/templates/home/contact.html
{% extends 'home/base.html' %}

{% block navbar %} {% include 'home/navbar.html' %} {% endblock %}


{% load static %}
{% block content %}
<!-- section -->
	<div class="section">
		<!-- container -->
		<div class="container">
			<!-- row -->
			<div class="row">
				<form id="checkout-form" class="clearfix" action="{% url 'home:contact' %}" method="POST">
				{% csrf_token %} 
					<div class="col-md-6">
						<div class="billing-details">
							
							<div class="section-title">
								<h3 class="title">Contact us</h3>
								{% if messages %}
                                            {% for message in messages %}
                                            <div class="alert alert-{{message.tags}}" role="alert">
                                                {{ message }}
                                            </div>
                                        {% endfor %}
                                {% endif %}
							</div>
							<div class="form-group">
								<input class="input" type="text" name="name" placeholder="your Name">
							</div>
							
							<div class="form-group">
								<input class="input" type="email" name="email" placeholder="your Email">
							</div>
							<div class="form-group">
								<input class="input" type="text" name="subject" placeholder="your Subject">
							</div>
							<div class="form-group">
							<textarea name="message" class="input" placeholder="your Message"></textarea>
							</div>
							
							<button class="primary-btn">Submit</button>
						</div>
					</div>
                    

					<div class="col-md-6">
						<div class="shiping-methods">
							<div class="section-title">
								<h4 class="title">Contact us</h4>
							</div>
							{{setting.contact|safe}}
						</div>
					</div>
                    </form>
</div>
			<!-- /row -->
		</div>
		<!-- /container -->
	</div>
	<!-- /section -->
    {% endblock %}

home/templates/home/footer.html
 
    {% load static %}
 <!-- FOOTER -->
	<footer id="footer" class="section section-grey">
		<!-- container -->
		<div class="container">
			<!-- row -->
			<div class="row">
				<!-- footer widget -->
				<div class="col-md-3 col-sm-6 col-xs-6">
					<div class="footer">
						<!-- footer logo -->
						<div class="footer-logo">
							<a class="logo" href="{% url 'home:home' %}">
		            <img src="{% static 'img/logo.png' %}" alt="">
		          </a>
						</div>
						<!-- /footer logo -->

						<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna</p>

						<!-- footer social -->
						<ul class="footer-social">
							<li><a href="#"><i class="fa fa-facebook"></i></a></li>
							<li><a href="#"><i class="fa fa-twitter"></i></a></li>
							<li><a href="#"><i class="fa fa-instagram"></i></a></li>
							<li><a href="#"><i class="fa fa-google-plus"></i></a></li>
							<li><a href="#"><i class="fa fa-pinterest"></i></a></li>
						</ul>
						<!-- /footer social -->
					</div>
				</div>
				<!-- /footer widget -->

				<!-- footer widget -->
				<div class="col-md-3 col-sm-6 col-xs-6">
					<div class="footer">
						<h3 class="footer-header">My Account</h3>
						<ul class="list-links">
							<li><a href="#">My Account</a></li>
							<li><a href="#">My Wishlist</a></li>
							<li><a href="#">Compare</a></li>
							<li><a href="#">Checkout</a></li>
							<li><a href="#">Login</a></li>
						</ul>
					</div>
				</div>
				<!-- /footer widget -->

				<div class="clearfix visible-sm visible-xs"></div>

				<!-- footer widget -->
				<div class="col-md-3 col-sm-6 col-xs-6">
					<div class="footer">
						<h3 class="footer-header">Customer Service</h3>
						<ul class="list-links">
							<li><a href="{% url 'home:about' %}">About Us</a></li>
							<li><a href="{% url 'home:contact' %}">Contact Us</a></li>
							<li><a href="#">Shiping & Return</a></li>
							<li><a href="#">Shiping Guide</a></li>
							<li><a href="#">FAQ</a></li>
						</ul>
					</div>
				</div>
				<!-- /footer widget -->

				<!-- footer subscribe -->
				<div class="col-md-3 col-sm-6 col-xs-6">
					<div class="footer">
						<h3 class="footer-header">Stay Connected</h3>
						<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor.</p>
						<form>
							<div class="form-group">
								<input class="input" placeholder="Enter Email Address">
							</div>
							<button class="primary-btn">Join Newslatter</button>
						</form>
					</div>
				</div>
				<!-- /footer subscribe -->
			</div>
			<!-- /row -->
			<hr>
			<!-- row -->
			<div class="row">
				<div class="col-md-8 col-md-offset-2 text-center">
					<!-- footer copyright -->
					<div class="footer-copyright">
						<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
						Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
						<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
					</div>
					<!-- /footer copyright -->
				</div>
			</div>
			<!-- /row -->
		</div>
		<!-- /container -->
	</footer>
    <!-- /FOOTER -->
  

home/templates/home/header.html
 {% load static %}
    <!-- HEADER -->
	<header>
		<!-- top Header -->
		<div id="top-header">
			<div class="container">
				<div class="pull-left">
					<span>Welcome to E-shop!</span>
					{% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-{{message.tags}}" role="alert">
                            {{ message |safe }}
                        </div>
                    {% endfor %}
                {% endif %}
				</div>
				<div class="pull-right">
					<ul class="header-top-links">
						<li><a href="#">Store</a></li>
						<li><a href="#">Newsletter</a></li>
						<li><a href="#">FAQ</a></li>
						<li class="dropdown default-dropdown">
							<a class="dropdown-toggle" data-toggle="dropdown" aria-expanded="true">ENG <i class="fa fa-caret-down"></i></a>
							<ul class="custom-menu">
								<li><a href="#">English (ENG)</a></li>
								<li><a href="#">Russian (Ru)</a></li>
								<li><a href="#">French (FR)</a></li>
								<li><a href="#">Spanish (Es)</a></li>
							</ul>
						</li>
						<li class="dropdown default-dropdown">
							<a class="dropdown-toggle" data-toggle="dropdown" aria-expanded="true">USD <i class="fa fa-caret-down"></i></a>
							<ul class="custom-menu">
								<li><a href="#">USD ($)</a></li>
								<li><a href="#">EUR (€)</a></li>
							</ul>
						</li>
					</ul>
				</div>
			</div>
		</div>
		<!-- /top Header -->

		<!-- header -->
		<div id="header">
			<div class="container">
				<div class="pull-left">
					<!-- Logo -->
					<div class="header-logo">
						<a class="logo" href="{% url 'home:home' %}">
							<img src="{% static 'img/logo.png' %}" alt="">
						</a>
					</div>
					<!-- /Logo -->
                  <script>
                    $(function() {
                        $("#query").autocomplete({
                            source: "{% url 'home:search_auto' %}",
                            select: function (event, ui) { //item selected
                                AutoCompleteSelectHandler(event, ui)
                            },
                            minLength: 2,
                        });
                    });
                    function AutoCompleteSelectHandler(event, ui)
                    {
                        var selectedObj = ui.item;
                    }
                </script>
					<!-- Search -->
					<div class="header-search">
						<form action="{% url 'home:search' %}" method="GET">
						 
							<input id="query" name="query" class="input search-input" type="text" placeholder="Enter your keyword">
							<select name="catid" class="input search-categories">
								<option value="0">All Categories</option>
							
							</select>
							<button class="search-btn"><i class="fa fa-search"></i></button>
						</form>
					</div>
					<!-- /Search -->
				</div>
				<div class="pull-right">
					<ul class="header-btns">
						<!-- Account -->
						<li class="header-account dropdown default-dropdown">
							<div class="dropdown-toggle" role="button" data-toggle="dropdown" aria-expanded="true">
							     {% if request.user.is_authenticated %}
							       <div class="header-btns-icon "> 
                                    <img src="{{ request.session.userimage }}" style="height: 40px; border-radius: 30%">
                                  </div> 
								  {% endif%}
								{% comment %} <div class="header-btns-icon">
									<i class="fa fa-user-o"></i>
								</div> {% endcomment %}
								<strong class="text-uppercase">{{request.user.username}} <i class="fa fa-caret-down"></i></strong>
							</div>
							 {% if request.user.is_authenticated %}
							 <a href="{% url 'accounts:logout' %}" class="text-uppercase">Logout</a>
							 {% else %}
							 <a href="{% url 'accounts:login' %}" class="text-uppercase">Login</a>
							 {% endif %}
							
							<ul class="custom-menu">
								<li><a href="{% url 'accounts:profile' %}"><i class="fa fa-user-o"></i> My Account</a></li>
								<li><a href="#"><i class="fa fa-heart-o"></i> My Wishlist</a></li>
								<li><a href="#"><i class="fa fa-exchange"></i> Compare</a></li>
								<li><a href="{% url 'cart:checkout' %}"><i class="fa fa-check"></i> Checkout</a></li>
								{% if not request.user.is_authenticated %}
								<li><a href="{% url 'accounts:login' %}"><i class="fa fa-unlock-alt"></i> Login</a></li>
								<li><a href="{% url 'accounts:register' %}"><i class="fa fa-user-plus"></i> Create An Account</a></li>
								{% else %}
								<li><a href="{% url 'accounts:password_change' %}"><i class="fa fa-unlock-alt"></i> Change password</a></li>
								{% endif%}
							</ul>
						</li>
						<!-- /Account -->

						<!-- Cart -->
						<li class="header-cart dropdown default-dropdown">
							<a href="{% url 'cart:shopcart' %}">
								<div class="header-btns-icon">
									<i class="fa fa-shopping-cart"></i>
									<span class="qty">{{cartpro}}</span>
								</div>
								<strong class="text-uppercase">My Cart:</strong>
								<br>
								
							</a>
							
						</li>
						<!-- /Cart -->

						<!-- Mobile nav toggle-->
						<li class="nav-toggle">
							<button class="nav-toggle-btn main-btn icon-btn"><i class="fa fa-bars"></i></button>
						</li>
						<!-- / Mobile nav toggle -->
					</ul>
				</div>
			</div>
			<!-- header -->
		</div>
		<!-- container -->
	</header>
    <!-- /HEADER -->
    

home/templates/home/navbar.html
 
    {% load static %}
	
<!-- NAVIGATION -->
	<div id="navigation">
		<!-- container -->
		<div class="container">
			<div id="responsive-nav">
               
                
                <!--category nav -->
				
				  <div class="category-nav show-on-click">
				
					<span class="category-header ">Categories <i class="fa fa-list"></i></span>
					{% load myapptags %}
					 {% categoryTree 0 '' as category %}
					<ul class="category-list">
						
					 {{ category | safe  }}
					</ul>
				</div>  
                <!-- /category nav-->
                


				<!-- menu nav -->
				<div class="menu-nav">
					<span class="menu-header">Menu <i class="fa fa-bars"></i></span>
					<ul class="menu-list">
						<li><a href="{% url 'home:home' %}">Home</a></li>
                        <li><a href="{% url 'product:product_list' %}">Shop</a></li>
						<li><a href="{% url 'home:contact' %}">Contact</a></li>

					</ul>
				</div>
				<!-- menu nav -->
			</div>
		</div>
		<!-- /container -->
	</div>
    <!--NAVIGATION-->
    

home/templates/home/search_product.html
{% extends 'home/base.html' %}

{% block title %} {{ setting.title }} {% endblock %}
{% block description %} {{ setting.description }} {% endblock %}
{% block keywords %} {{ setting.keywords }} {% endblock %}

{% block navbar %} {% include 'home/navbar.html' %} {% endblock %}


{% load static %}
{% block content %}
<!-- BREADCRUMB -->
	<div id="breadcrumb">
		<div class="container">
			<ul class="breadcrumb">
				<li><a href="/">Home</a></li>
				<li class="active">{{ query }} results</li>
			</ul>
		</div>
	</div>
	<!-- /BREADCRUMB -->
<!-- section -->
	<div class="section">
		<!-- container -->
		<div class="container">
			<!-- row -->
			<div class="row">

				<!-- MAIN -->
				<div id="main" class="col-md-12">
					<!-- STORE -->
					<div id="store">
						<!-- row -->
						<div class="row">
                        <div class="col-md-12">
						<div class="order-summary clearfix">
							<div class="section-title">
								<h3 class="title">search result</h3>
							</div>
							<table class="shopping-cart-table table">
								<thead>
									<tr>
										<th>Product</th>
										<th></th>
										<th class="text-center">Price</th>
										<th class="text-center">category</th>
										<th class="text-center">quantity</th>
										<th class="text-right"></th>
									</tr>
								</thead>
								<tbody>
                                {% for item in product %}
									<tr>
										<td class="thumb"><a href="{% url 'home:product_detail' item.id  item.slug %}"><img src="{{item.image.url}}" alt="" style="height:100px"></a></td>
										<td class="details">
											<a href="#">{{item.title}}</a>
											<ul>
												<li><span>Size: XL</span></li>
												<li><span>Color: Camelot</span></li>
											</ul>
										</td>
										<td class="price text-center"><strong>{{item.price}}</strong><br><del class="font-weak"><small>$40.00</small></del></td>
										<td class="qty text-center">*********</td>
										<td class="total text-center"><strong class="primary-color">{{item.amount}}</strong></td>
										
									</tr>
                                    {% endfor %}
									
								</tbody>
                            </table>
                        </div>
                </div>
                </div>
                </div>
                <!-- store bottom filter -->
					<div class="store-filter clearfix">
						<div class="pull-left">
							<div class="row-filter">
								<a href="#"><i class="fa fa-th-large"></i></a>
								<a href="#" class="active"><i class="fa fa-bars"></i></a>
							</div>
							<div class="sort-filter">
								<span class="text-uppercase">Sort By:</span>
								<select class="input">
										<option value="0">Position</option>
										<option value="0">Price</option>
										<option value="0">Rating</option>
									</select>
								<a href="#" class="main-btn icon-btn"><i class="fa fa-arrow-down"></i></a>
							</div>
						</div>
						<div class="pull-right">
							<div class="page-filter">
								<span class="text-uppercase">Show:</span>
								<select class="input">
										<option value="0">10</option>
										<option value="1">20</option>
										<option value="2">30</option>
									</select>
							</div>
							<ul class="store-pages">
								<li><span class="text-uppercase">Page:</span></li>
								<li class="active">1</li>
								<li><a href="#">2</a></li>
								<li><a href="#">3</a></li>
								<li><a href="#"><i class="fa fa-caret-right"></i></a></li>
							</ul>
						</div>
					</div>
					<!-- /store bottom filter -->
				</div>
				<!-- /MAIN -->
			</div>
			<!-- /row -->
		</div>
		<!-- /container -->
	</div>
	<!-- /section -->

    {% endblock %}

home/templates/home/slider.html
{%  load static %}
<!-- HOME -->
	<div id="home">
		<!-- container -->
		<div class="container">
			<!-- home wrap -->
			<div class="home-wrap">
				<!-- home slick -->
				<div id="home-slick">

               {% for item in  product_slider %}
					<!-- banner -->
					<div class="banner banner-1">
						<img src="{{item.image.url}}" alt=""  width="450" height="450">
						<div class="banner-caption text-center">
							<!-- <h1 class="white-color font-weak">{{item.title}}</h1> -->
							<h3 class="white-color font-weak">${{item.price}}</h3>
							<a href="{% url 'home:product_detail' item.id item.slug %}"><button class="primary-btn">Shop Now</button></a>
						</div>
					</div>
					<!-- /banner -->

				{% endfor %}

					
				</div>
				<!-- /home slick -->
			</div>
			<!-- /home wrap -->
		</div>
		<!-- /container -->
	</div>
    <!-- /HOME -->
   